plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jarvis.fa'
    compileSdk 35

    defaultConfig {
        applicationId "com.jarvis.fa"
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName "6.0-core"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
