package com.jarvis.fa;
import android.content.*;import android.os.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.*;
public class BrainEngine{
 public interface Callback{void onResult(String reply);} private final SharedPreferences p; private final ExecutorService ex=Executors.newSingleThreadExecutor(); private final MemoryStore memoryStore;
 public BrainEngine(Context c){p=c.getSharedPreferences("jarvis_data",Context.MODE_PRIVATE);memoryStore=new MemoryStore(c);}
 public boolean isConfigured(){return !p.getString("aiEndpoint","").trim().isEmpty()&&!p.getString("aiModel","").trim().isEmpty();}
 public void ask(String q,String memory,Callback cb){String n=q==null?"":q.trim();if(n.startsWith("یادت باشه")||n.startsWith("به خاطر بسپار")){String fact=n.replaceFirst("^(یادت باشه|به خاطر بسپار)\\s*","").trim();if(!fact.isEmpty()){memoryStore.remember(fact);memoryStore.addTurn("user",n);String r="یادم می‌ماند: "+fact;memoryStore.addTurn("assistant",r);cb.onResult(r);return;}}memoryStore.addTurn("user",n);if(!isConfigured()){String r="مغز آنلاین هنوز متصل نیست. از تنظیم AI، آدرس سرویس، مدل و کلید خودت را وارد کن.";memoryStore.addTurn("assistant",r);cb.onResult(r);return;}ex.submit(()->{String r;try{String all=(memory==null?"":memory)+"\n\n"+memoryStore.context();r=call(n,all);}catch(Exception e){r="اتصال هوش مصنوعی برقرار نشد. اینترنت و تنظیمات AI را بررسی کن.";}memoryStore.addTurn("assistant",r);String out=r;new Handler(Looper.getMainLooper()).post(()->cb.onResult(out));});}
 private String call(String q,String memory)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(p.getString("aiEndpoint","").trim()).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(15000);c.setReadTimeout(60000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");String key=p.getString("aiKey","").trim();if(!key.isEmpty())c.setRequestProperty("Authorization","Bearer "+key);JSONObject body=new JSONObject();body.put("model",p.getString("aiModel","").trim());body.put("temperature",0.3);JSONArray ms=new JSONArray();ms.put(new JSONObject().put("role","system").put("content","تو JARVIS، دستیار شخصی فارسی‌زبان کاربر هستی. دقیق، کوتاه و اجرایی پاسخ بده. از حافظه داده‌شده برای پیوستگی استفاده کن. هرگز ادعا نکن عملی روی گوشی انجام شده مگر موتور محلی آن را اجرا کرده باشد. اگر درخواست کاربر قابل انجام محلی نیست، روشن بگو چه چیزی لازم است."));if(memory!=null&&!memory.trim().isEmpty())ms.put(new JSONObject().put("role","system").put("content",memory));ms.put(new JSONObject().put("role","user").put("content",q));body.put("messages",ms);try(OutputStream os=c.getOutputStream()){os.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream is=code>=200&&code<300?c.getInputStream():c.getErrorStream();String text=read(is);if(code<200||code>=300)throw new IOException("HTTP "+code+" "+text);JSONObject root=new JSONObject(text);JSONArray ch=root.optJSONArray("choices");if(ch==null||ch.length()==0)return "پاسخی دریافت نشد.";JSONObject msg=ch.getJSONObject(0).optJSONObject("message");return msg==null?"پاسخی دریافت نشد.":msg.optString("content","پاسخی دریافت نشد.");}
 private String read(InputStream is)throws Exception{if(is==null)return "";ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=is.read(b))!=-1)o.write(b,0,n);return o.toString("UTF-8");}
 public void shutdown(){ex.shutdownNow();}
}
