package com.jarvis.fa;
import android.content.*;import android.os.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.*;
public class BrainEngine{
 public interface Callback{void onResult(String reply);} private final SharedPreferences p; private final ExecutorService ex=Executors.newSingleThreadExecutor(); private final MemoryStore memoryStore;
 private static final String ENDPOINT="https://api.openai.com/v1/responses"; private static final String MODEL="gpt-5.6-luna";
 public BrainEngine(Context c){p=c.getSharedPreferences("jarvis_data",Context.MODE_PRIVATE);memoryStore=new MemoryStore(c);p.edit().putString("aiEndpoint",ENDPOINT).putString("aiModel",MODEL).apply();}
 public void configureOpenAI(String key){p.edit().putString("aiEndpoint",ENDPOINT).putString("aiModel",MODEL).putString("aiKey",key==null?"":key.trim()).apply();}
 public String model(){return MODEL;}
 public boolean isConfigured(){return !p.getString("aiKey","").trim().isEmpty();}
 public void test(Callback cb){runRequest("فقط دقیقاً بنویس: اتصال برقرار است","تست اتصال",cb,false);}
 public void ask(String q,String memory,Callback cb){String n=q==null?"":q.trim();if(n.startsWith("یادت باشه")||n.startsWith("به خاطر بسپار")){String fact=n.replaceFirst("^(یادت باشه|به خاطر بسپار)\\s*","").trim();if(!fact.isEmpty()){memoryStore.remember(fact);memoryStore.addTurn("user",n);String r="یادم می‌ماند: "+fact;memoryStore.addTurn("assistant",r);cb.onResult(r);return;}}memoryStore.addTurn("user",n);String all=(memory==null?"":memory)+"\n\n"+memoryStore.context();runRequest(n,all,cb,true);}
 private void runRequest(String q,String memory,Callback cb,boolean store){if(!isConfigured()){cb.onResult("برای اتصال هوش مصنوعی، دکمه OpenAI را بزن و API Key جدیدت را وارد کن.");return;}ex.submit(()->{String r;try{r=call(q,memory);}catch(Exception e){r=prettyError(e.getMessage());}if(store)memoryStore.addTurn("assistant",r);String out=r;new Handler(Looper.getMainLooper()).post(()->cb.onResult(out));});}
 private String prettyError(String m){if(m==null)m="";if(m.startsWith("HTTP 401"))return "خطای 401: API Key نامعتبر یا غیرفعال است. یک کلید جدید بساز و دوباره وارد کن.";if(m.startsWith("HTTP 429"))return "خطای 429: اعتبار API کافی نیست یا سقف مصرف حساب پر شده است.";if(m.startsWith("HTTP 403"))return "خطای 403: این API Key اجازه دسترسی به سرویس یا مدل را ندارد.";if(m.startsWith("HTTP 404"))return "خطای 404: مدل یا مسیر API در دسترس نیست.";if(m.startsWith("HTTP 400"))return "خطای 400 از OpenAI: "+extractApiMessage(m);if(m.contains("UnknownHost")||m.contains("Unable to resolve host"))return "اتصال اینترنت یا DNS گوشی به api.openai.com برقرار نیست.";if(m.contains("timeout")||m.contains("timed out"))return "اتصال به OpenAI زمان‌بر شد و قطع شد. اینترنت را بررسی کن.";return "اتصال OpenAI برقرار نشد: "+extractApiMessage(m);}
 private String extractApiMessage(String m){int i=m.indexOf('{');if(i>=0){try{JSONObject j=new JSONObject(m.substring(i));JSONObject e=j.optJSONObject("error");if(e!=null){String x=e.optString("message","");if(!x.isEmpty())return x;}}catch(Exception ignored){}}return m.length()>220?m.substring(0,220):m;}
 private String call(String q,String memory)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(ENDPOINT).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(20000);c.setReadTimeout(90000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");c.setRequestProperty("Authorization","Bearer "+p.getString("aiKey","").trim());JSONObject body=new JSONObject();body.put("model",MODEL);String instructions="تو JARVIS، دستیار شخصی فارسی‌زبان کاربر هستی. دقیق، کوتاه و اجرایی پاسخ بده. از حافظه داده‌شده برای پیوستگی استفاده کن. هرگز ادعا نکن عملی روی گوشی انجام شده مگر موتور محلی آن را اجرا کرده باشد.";if(memory!=null&&!memory.trim().isEmpty())instructions+="\n\nحافظه و زمینه:\n"+memory;body.put("instructions",instructions);body.put("input",q);try(OutputStream os=c.getOutputStream()){os.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream is=code>=200&&code<300?c.getInputStream():c.getErrorStream();String txt=read(is);if(code<200||code>=300)throw new IOException("HTTP "+code+" "+txt);JSONObject root=new JSONObject(txt);String out=parseText(root);return out.isEmpty()?"پاسخی دریافت نشد.":out;}
 private String parseText(JSONObject root){StringBuilder sb=new StringBuilder();JSONArray out=root.optJSONArray("output");if(out==null)return "";for(int i=0;i<out.length();i++){JSONObject item=out.optJSONObject(i);if(item==null)continue;JSONArray content=item.optJSONArray("content");if(content==null)continue;for(int j=0;j<content.length();j++){JSONObject part=content.optJSONObject(j);if(part==null)continue;if("output_text".equals(part.optString("type"))){String t=part.optString("text","");if(!t.isEmpty()){if(sb.length()>0)sb.append('\n');sb.append(t);}}}}return sb.toString().trim();}
 private String read(InputStream is)throws Exception{if(is==null)return "";ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=is.read(b))!=-1)o.write(b,0,n);return o.toString("UTF-8");}
 public void shutdown(){ex.shutdownNow();}
}
