package com.jarvis.fa;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.provider.Settings;import android.speech.*;import android.speech.tts.TextToSpeech;import android.text.InputType;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;

public class MainActivity extends Activity implements TextToSpeech.OnInitListener{
 SharedPreferences p; TextToSpeech tts; SpeechRecognizer sr; TextView status,heard; EditText input; LinearLayout log; BrainEngine brain; JarvisActions actions; BroadcastReceiver wakeReceiver; boolean listening=false;
 int bg=Color.rgb(3,10,20),panel=Color.rgb(10,24,40),panel2=Color.rgb(7,18,32),text=Color.WHITE,muted=Color.rgb(150,180,200),accent=Color.rgb(54,224,255),accent2=Color.rgb(0,135,190);
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("jarvis_data",MODE_PRIVATE);tts=new TextToSpeech(this,this);brain=new BrainEngine(this);actions=new JarvisActions(this);build();permissions();recognizer();wakeReceiver();String pending=p.getString("pendingWakeCommand","");if(!pending.isEmpty()){p.edit().remove("pendingWakeCommand").apply();handle(pending);}}
 int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;} GradientDrawable stroke(int color,int radius,int strokeColor){GradientDrawable g=round(color,radius);g.setStroke(dp(1),strokeColor);return g;}
 TextView tv(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(text);v.setTextSize(sp);v.setPadding(dp(14),dp(10),dp(14),dp(10));return v;}
 TextView label(String s){TextView v=tv(s,12);v.setTextColor(muted);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(text);b.setTextSize(13);b.setAllCaps(false);b.setBackground(stroke(panel,16,Color.rgb(24,74,99)));b.setPadding(dp(8),0,dp(8),0);return b;}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(stroke(panel2,20,Color.rgb(18,70,98)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(8),0,dp(8));c.setLayoutParams(lp);return c;}
 void build(){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(22),dp(18),dp(26));root.setBackgroundColor(bg);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
  LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setGravity(Gravity.CENTER);TextView title=tv("J A R V I S",31);title.setTextColor(accent);title.setGravity(Gravity.CENTER);title.setLetterSpacing(.16f);top.addView(title);TextView sub=tv("V6 • PERSONAL AI SYSTEM",11);sub.setTextColor(muted);sub.setGravity(Gravity.CENTER);top.addView(sub);root.addView(top);
  LinearLayout core=card();core.setGravity(Gravity.CENTER);TextView coreIcon=tv("◉",64);coreIcon.setTextColor(accent);coreIcon.setGravity(Gravity.CENTER);core.addView(coreIcon);status=tv("سیستم آماده است",15);status.setTextColor(accent);status.setGravity(Gravity.CENTER);core.addView(status);heard=tv("بگو: «سلام جارویس» یا دستور خودت را بنویس.",14);heard.setTextColor(muted);heard.setGravity(Gravity.CENTER);core.addView(heard);Button mic=new Button(this);mic.setText("🎙  صحبت با جارویس");mic.setTextColor(Color.rgb(0,20,28));mic.setTextSize(17);mic.setAllCaps(false);mic.setBackground(round(accent,28));LinearLayout.LayoutParams mlp=new LinearLayout.LayoutParams(-1,dp(58));mlp.setMargins(dp(18),dp(10),dp(18),dp(6));core.addView(mic,mlp);mic.setOnClickListener(v->listen());root.addView(core);
  root.addView(label("دسترسی سریع"));LinearLayout quick=new LinearLayout(this);quick.setOrientation(LinearLayout.HORIZONTAL);String[] qs={"🔦 چراغ","📡 وای‌فای","🧭 نقشه"};for(String s:qs){Button b=btn(s);quick.addView(b,new LinearLayout.LayoutParams(0,dp(52),1));if(s.contains("چراغ"))b.setOnClickListener(v->handle("چراغ روشن"));if(s.contains("وای"))b.setOnClickListener(v->handle("وای فای"));if(s.contains("نقشه"))b.setOnClickListener(v->handle("نقشه مشهد"));}root.addView(quick);
  LinearLayout tools=new LinearLayout(this);tools.setOrientation(LinearLayout.HORIZONTAL);Button wake=btn("◌ Wake Word");wake.setOnClickListener(v->toggleWake());tools.addView(wake,new LinearLayout.LayoutParams(0,dp(48),1));Button micTest=btn("✓ تست میکروفون");micTest.setOnClickListener(v->micDiagnostic());tools.addView(micTest,new LinearLayout.LayoutParams(0,dp(48),1));Button set=btn("✦ OpenAI");set.setOnClickListener(v->aiDialog());tools.addView(set,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(tools);
  root.addView(label("فرمان متنی"));LinearLayout ask=card();input=new EditText(this);input.setHint("مثلاً: امروز چه کارهایی دارم؟");input.setHintTextColor(Color.rgb(105,135,155));input.setTextColor(text);input.setTextSize(15);input.setSingleLine(false);input.setMinHeight(dp(52));input.setBackground(stroke(Color.rgb(5,14,26),16,Color.rgb(20,72,95)));input.setPadding(dp(14),dp(12),dp(14),dp(12));ask.addView(input);Button send=new Button(this);send.setText("ارسال به جارویس  ←");send.setTextColor(accent);send.setTextSize(14);send.setAllCaps(false);send.setBackground(stroke(Color.TRANSPARENT,14,accent2));LinearLayout.LayoutParams slp=new LinearLayout.LayoutParams(-1,dp(50));slp.setMargins(0,dp(10),0,0);ask.addView(send,slp);send.setOnClickListener(v->{String q=input.getText().toString().trim();if(!q.isEmpty()){input.setText("");handle(q);}});root.addView(ask);
  root.addView(label("گزارش مکالمه"));log=new LinearLayout(this);log.setOrientation(LinearLayout.VERTICAL);root.addView(log);sc.addView(root);setContentView(sc);}
 void add(String who,String s){LinearLayout bubble=card();TextView w=tv(who.equals("JARVIS")?"JARVIS":"شما",11);w.setTextColor(who.equals("JARVIS")?accent:muted);bubble.addView(w);TextView m=tv(s,15);m.setPadding(dp(14),dp(2),dp(14),dp(8));bubble.addView(m);log.addView(bubble,0);}
 void reply(String s){add("JARVIS",s);speak(s);status.setText("سیستم آماده است");}
 void handle(String raw){String q=raw.trim();if(q.isEmpty())return;add("شما",q);heard.setText(q);status.setText("در حال پردازش فرمان...");String n=q.replace('ي','ی').replace('ك','ک').toLowerCase(Locale.ROOT);if(n.contains("ساعت")){reply("الان ساعت "+new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date())+" است.");return;}if(n.contains("تاریخ")||n.contains("امروز چند")){reply("امروز "+new SimpleDateFormat("yyyy/MM/dd",Locale.getDefault()).format(new Date())+" است.");return;}if(n.contains("چراغ")&&(n.contains("روشن")||n.contains("فعال"))){reply(actions.flashlight(true)?"چراغ‌قوه روشن شد.":"نتوانستم چراغ‌قوه را روشن کنم.");return;}if(n.contains("چراغ")&&(n.contains("خاموش")||n.contains("ببند"))){reply(actions.flashlight(false)?"چراغ‌قوه خاموش شد.":"نتوانستم چراغ‌قوه را خاموش کنم.");return;}if(n.contains("وای فای")||n.contains("وای‌فای")){actions.settings(Settings.ACTION_WIFI_SETTINGS);reply("تنظیمات وای‌فای باز شد.");return;}if(n.contains("بلوتوث")){actions.settings(Settings.ACTION_BLUETOOTH_SETTINGS);reply("تنظیمات بلوتوث باز شد.");return;}if(n.contains("واتساپ")){reply(actions.openApp("com.whatsapp")?"واتساپ باز شد.":"واتساپ پیدا نشد.");return;}if(n.contains("تلگرام")){reply(actions.openApp("org.telegram.messenger")?"تلگرام باز شد.":"تلگرام پیدا نشد.");return;}if(n.contains("اینستاگرام")){reply(actions.openApp("com.instagram.android")?"اینستاگرام باز شد.":"اینستاگرام پیدا نشد.");return;}if(n.startsWith("جستجو ")||n.startsWith("سرچ ")){actions.webSearch(q.substring(q.indexOf(' ')+1));reply("جستجو را باز کردم.");return;}if(n.startsWith("نقشه ")||n.startsWith("مسیر ")){actions.openMaps(q.substring(q.indexOf(' ')+1));reply("نقشه را باز کردم.");return;}if(n.startsWith("تماس ")){String num=q.replaceAll("[^0-9+]","");if(!num.isEmpty()){actions.dial(num);reply("شماره‌گیر باز شد.");return;}}brain.ask(q,memory(),this::reply);}
 String memory(){return "نام دستیار: جارویس. Wake word: "+p.getString("wakeWord","جارویس")+".";}
 void recognizer(){if(!SpeechRecognizer.isRecognitionAvailable(this)){status.setText("سرویس تشخیص گفتار در دسترس نیست");return;}try{if(sr!=null)sr.destroy();sr=SpeechRecognizer.createSpeechRecognizer(this);sr.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle b){listening=true;status.setText("گوش می‌دهم... صحبت کن");}public void onBeginningOfSpeech(){status.setText("صدایت دریافت شد...");}public void onRmsChanged(float x){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){status.setText("در حال تبدیل صدا به متن...");}public void onError(int e){listening=false;String m=speechError(e);status.setText(m);heard.setText(m);}public void onResults(Bundle b){listening=false;ArrayList<String>x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty()){heard.setText("شنیدم: "+x.get(0));handle(x.get(0));}else status.setText("چیزی تشخیص داده نشد");}public void onPartialResults(Bundle b){ArrayList<String>x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty())heard.setText("... "+x.get(0));}public void onEvent(int a,Bundle b){}});}catch(Exception e){sr=null;status.setText("راه‌اندازی میکروفون ناموفق بود");}}
 String speechError(int e){switch(e){case SpeechRecognizer.ERROR_AUDIO:return "خطای صوتی (3): میکروفون یا سرویس صوتی مشکل دارد";case SpeechRecognizer.ERROR_CLIENT:return "خطای سرویس (5): دوباره دکمه میکروفون را بزن";case SpeechRecognizer.ERROR_INSUFFICIENT_PERMISSIONS:return "مجوز میکروفون داده نشده است";case SpeechRecognizer.ERROR_NETWORK:return "خطای شبکه تشخیص گفتار";case SpeechRecognizer.ERROR_NETWORK_TIMEOUT:return "زمان اتصال تشخیص گفتار تمام شد";case SpeechRecognizer.ERROR_NO_MATCH:return "صدا دریافت شد ولی گفتار تشخیص داده نشد";case SpeechRecognizer.ERROR_RECOGNIZER_BUSY:return "میکروفون مشغول است؛ دوباره امتحان کن";case SpeechRecognizer.ERROR_SERVER:return "سرویس تشخیص گفتار گوشی خطا داد";case SpeechRecognizer.ERROR_SPEECH_TIMEOUT:return "صدایی دریافت نشد؛ بعد از زدن دکمه صحبت کن";default:return "خطای تشخیص گفتار، کد "+e;}}
 void micDiagnostic(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){status.setText("اول مجوز میکروفون را فعال کن");requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},101);return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){status.setText("Google Speech Recognition در دسترس نیست");heard.setText("Speech Services by Google یا Google app را فعال/به‌روزرسانی کن.");return;}status.setText("MIC ✓   SPEECH SERVICE ✓");heard.setText("تست آماده است؛ دکمه میکروفون را بزن و بگو: سلام جارویس");}
 void listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},101);return;}if(listening&&sr!=null){try{sr.cancel();}catch(Exception ignored){}listening=false;}if(sr==null)recognizer();if(sr==null)return;Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_PREFERENCE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);i.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,3);i.putExtra(RecognizerIntent.EXTRA_CALLING_PACKAGE,getPackageName());try{sr.startListening(i);}catch(Exception e){recognizer();status.setText("سرویس میکروفون ریست شد؛ دوباره بزن");}}
 void toggleWake(){boolean on=!p.getBoolean("wakeEnabled",false);p.edit().putBoolean("wakeEnabled",on).apply();Intent i=new Intent(this,WakeWordService.class);if(on){i.setAction(WakeWordService.ACTION_START);try{if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);reply("حالت شنود جارویس فعال شد.");}catch(Exception e){p.edit().putBoolean("wakeEnabled",false).apply();reply("فعال‌سازی شنود پس‌زمینه توسط اندروید محدود شد.");}}else{i.setAction(WakeWordService.ACTION_STOP);try{startService(i);}catch(Exception ignored){}reply("حالت شنود خاموش شد.");}}
 void wakeReceiver(){wakeReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){String q=i.getStringExtra("command");if(q!=null&&!q.trim().isEmpty())handle(q);}};IntentFilter f=new IntentFilter("com.jarvis.fa.WAKE_COMMAND");if(Build.VERSION.SDK_INT>=33)registerReceiver(wakeReceiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(wakeReceiver,f);}
 void aiDialog(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(24),dp(8),dp(24),dp(8));TextView info=tv("اتصال OpenAI آماده است. فقط API Key خودت را وارد کن.\nModel: "+brain.model(),14);info.setTextColor(Color.DKGRAY);EditText key=new EditText(this);key.setHint("sk-... API Key");key.setText(p.getString("aiKey",""));key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);l.addView(info);l.addView(key);new AlertDialog.Builder(this).setTitle("اتصال OpenAI").setView(l).setPositiveButton("ذخیره و تست",(d,w)->{brain.configureOpenAI(key.getText().toString());status.setText("در حال تست OpenAI...");brain.test(this::reply);}).setNegativeButton("انصراف",null).show();}
 void permissions(){ArrayList<String>a=new ArrayList<>();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)a.add(Manifest.permission.RECORD_AUDIO);if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)a.add(Manifest.permission.CAMERA);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)a.add(Manifest.permission.POST_NOTIFICATIONS);if(!a.isEmpty())requestPermissions(a.toArray(new String[0]),100);}
 @Override public void onRequestPermissionsResult(int r,String[] ps,int[] g){super.onRequestPermissionsResult(r,ps,g);if(r==101){if(g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED){status.setText("مجوز میکروفون فعال شد");recognizer();}else status.setText("بدون مجوز میکروفون، فرمان صوتی کار نمی‌کند");}}
 @Override public void onInit(int s){if(s==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("fa","IR"));tts.setSpeechRate(.95f);}}
 void speak(String s){if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"jarvis");}
 @Override protected void onDestroy(){try{unregisterReceiver(wakeReceiver);}catch(Exception ignored){}if(sr!=null)sr.destroy();if(tts!=null)tts.shutdown();if(brain!=null)brain.shutdown();super.onDestroy();}
}
