package com.jarvis.fa;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.view.*;import android.widget.*;import androidx.core.content.FileProvider;import java.io.*;import java.text.SimpleDateFormat;import java.util.*;

public class VisionActivity extends Activity{
    private static final int REQ_CAMERA=301,REQ_GALLERY=302,REQ_PERMISSION=303;
    private Bitmap image;private ImageView preview;private EditText prompt;private TextView answer,status,meta,actionInfo;private Button executeAction;
    private VisionEngine engine;private StructuredMemory memory;private VisionActionRouter actionRouter;private VisionAgentResult lastResult;private String lastQuestion="";private File cameraFile;private Uri cameraUri;
    private int bg=Color.rgb(3,10,20),panel=Color.rgb(8,21,36),panel2=Color.rgb(11,29,48),text=Color.WHITE,muted=Color.rgb(150,180,200),accent=Color.rgb(54,224,255);
    @Override public void onCreate(Bundle b){super.onCreate(b);engine=new VisionEngine(this);memory=new StructuredMemory(this);actionRouter=new VisionActionRouter(this);build();}
    int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(text);v.setTextSize(z);v.setPadding(dp(12),dp(9),dp(12),dp(9));return v;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(12),dp(12),dp(12));c.setBackgroundColor(panel);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(lp);return c;}
    void build(){ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(18),dp(16),dp(24));r.setBackgroundColor(bg);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
        TextView title=tv("JARVIS VISION AGENT",27);title.setTextColor(accent);title.setGravity(Gravity.CENTER);r.addView(title);TextView sub=tv("Full‑Resolution Vision • استخراج • تصمیم • اقدام با تأیید",12);sub.setTextColor(muted);sub.setGravity(Gravity.CENTER);r.addView(sub);
        preview=new ImageView(this);preview.setBackgroundColor(panel);preview.setScaleType(ImageView.ScaleType.CENTER_CROP);r.addView(preview,new LinearLayout.LayoutParams(-1,dp(300)));
        LinearLayout pick=new LinearLayout(this);Button cam=btn("📷 دوربین Full‑Res");cam.setOnClickListener(v->camera());pick.addView(cam,new LinearLayout.LayoutParams(0,dp(52),1));Button gal=btn("🖼 گالری");gal.setOnClickListener(v->gallery());pick.addView(gal,new LinearLayout.LayoutParams(0,dp(52),1));r.addView(pick);
        LinearLayout presets=new LinearLayout(this);Button identify=btn("شناسايی");identify.setOnClickListener(v->prompt.setText("این تصویر یا شیء را شناسایی کن، جزئیات قابل مشاهده را بگو و اگر اقدام مفیدی وجود دارد پیشنهاد بده."));presets.addView(identify,new LinearLayout.LayoutParams(0,dp(46),1));Button read=btn("خواندن متن");read.setOnClickListener(v->prompt.setText("تمام متن و اطلاعات مهم قابل خواندن در تصویر را دقیق استخراج کن و نوع سند را تشخیص بده."));presets.addView(read,new LinearLayout.LayoutParams(0,dp(46),1));Button act=btn("پیشنهاد اقدام");act.setOnClickListener(v->prompt.setText("این تصویر را تحلیل کن و اگر اقدام عملی امن و مفیدی مثل جستجو، نقشه، یادآوری، تقویم، ایمیل یا ذخیره در حافظه مناسب است پیشنهاد بده."));presets.addView(act,new LinearLayout.LayoutParams(0,dp(46),1));r.addView(presets);
        prompt=new EditText(this);prompt.setTextColor(text);prompt.setHintTextColor(muted);prompt.setHint("مثلاً: این قطعه چیست؟ متن این فاکتور را بخوان. این آدرس را روی نقشه باز کن. از تاریخ روی برگه یادآوری بساز.");prompt.setMinLines(2);r.addView(prompt);
        Button analyze=btn("◈ تحلیل و تصمیم توسط JARVIS Vision");analyze.setOnClickListener(v->analyze());r.addView(analyze,new LinearLayout.LayoutParams(-1,dp(58)));
        status=tv("VISION • آماده",12);status.setTextColor(accent);r.addView(status);
        LinearLayout resultCard=card();answer=tv("هنوز تصویری تحلیل نشده است.",15);resultCard.addView(answer);meta=tv("",12);meta.setTextColor(muted);resultCard.addView(meta);r.addView(resultCard);
        LinearLayout actionCard=card();TextView actionTitle=tv("ACTION",12);actionTitle.setTextColor(accent);actionCard.addView(actionTitle);actionInfo=tv("فعلاً اقدامی پیشنهاد نشده است.",14);actionCard.addView(actionInfo);executeAction=btn("✓ بررسی و اجرای اقدام پیشنهادی");executeAction.setEnabled(false);executeAction.setOnClickListener(v->confirmAction());actionCard.addView(executeAction,new LinearLayout.LayoutParams(-1,dp(54)));r.addView(actionCard);
        LinearLayout bottom=new LinearLayout(this);Button save=btn("💾 ذخیره تحلیل");save.setOnClickListener(v->save());bottom.addView(save,new LinearLayout.LayoutParams(0,dp(50),1));Button copy=btn("📋 کپی متن");copy.setOnClickListener(v->copyExtracted());bottom.addView(copy,new LinearLayout.LayoutParams(0,dp(50),1));Button again=btn("↻ سؤال بعدی");again.setOnClickListener(v->{prompt.requestFocus();prompt.setSelection(prompt.length());});bottom.addView(again,new LinearLayout.LayoutParams(0,dp(50),1));r.addView(bottom);
        sc.addView(r);setContentView(sc);}
    void resetResult(){lastResult=null;lastQuestion="";answer.setText("سؤالت را بنویس و تحلیل را بزن.");meta.setText("");actionInfo.setText("فعلاً اقدامی پیشنهاد نشده است.");executeAction.setEnabled(false);}
    void camera(){if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},REQ_PERMISSION);return;}try{File dir=new File(getCacheDir(),"vision");if(!dir.exists()&&!dir.mkdirs())throw new IOException("cache dir");cameraFile=File.createTempFile("jarvis_vision_",".jpg",dir);cameraUri=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",cameraFile);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);i.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(i,REQ_CAMERA);status.setText("VISION • دوربین Full‑Resolution باز شد");}catch(Exception e){new DiagnosticStore(this).error("VISION_CAMERA",e);status.setText("دوربین Full‑Resolution در دسترس نیست.");}}
    void gallery(){try{Intent i=new Intent(Intent.ACTION_GET_CONTENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(Intent.createChooser(i,"انتخاب تصویر"),REQ_GALLERY);}catch(Exception e){new DiagnosticStore(this).error("VISION_GALLERY",e);status.setText("گالری باز نشد.");}}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_PERMISSION&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)camera();else if(r==REQ_PERMISSION)status.setText("مجوز دوربین داده نشد.");}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK){if(req==REQ_CAMERA)cleanupCameraFile();return;}try{Bitmap next=null;if(req==REQ_CAMERA&&cameraFile!=null&&cameraFile.exists()&&cameraFile.length()>0){next=decodeFileSampled(cameraFile,2200);cleanupCameraFile();}else if(req==REQ_GALLERY&&data!=null){Uri u=data.getData();if(u!=null)next=decodeUriSampled(u,2200);}if(next!=null){if(image!=null&&!image.isRecycled())image.recycle();image=next;preview.setImageBitmap(image);status.setText("VISION • تصویر با کیفیت بالا آماده تحلیل");resetResult();}else status.setText("تصویر قابل خواندن نبود.");}catch(Exception e){new DiagnosticStore(this).error("VISION_DECODE",e);status.setText("خواندن تصویر ممکن نشد.");cleanupCameraFile();}}
    Bitmap decodeFileSampled(File f,int max)throws Exception{BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeFile(f.getAbsolutePath(),o);o.inSampleSize=sample(o.outWidth,o.outHeight,max);o.inJustDecodeBounds=false;o.inPreferredConfig=Bitmap.Config.ARGB_8888;Bitmap b=BitmapFactory.decodeFile(f.getAbsolutePath(),o);if(b==null)throw new IOException("decode file");return b;}
    Bitmap decodeUriSampled(Uri u,int max)throws Exception{BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;try(InputStream in=getContentResolver().openInputStream(u)){BitmapFactory.decodeStream(in,null,o);}o.inSampleSize=sample(o.outWidth,o.outHeight,max);o.inJustDecodeBounds=false;o.inPreferredConfig=Bitmap.Config.ARGB_8888;try(InputStream in=getContentResolver().openInputStream(u)){Bitmap b=BitmapFactory.decodeStream(in,null,o);if(b==null)throw new IOException("decode uri");return b;}}
    int sample(int w,int h,int max){int s=1;while(w/s>max||h/s>max)s*=2;return Math.max(1,s);}
    void cleanupCameraFile(){try{if(cameraFile!=null&&cameraFile.exists())cameraFile.delete();}catch(Exception ignored){}cameraFile=null;cameraUri=null;}
    void analyze(){if(image==null){status.setText("اول عکس بگیر یا از گالری انتخاب کن.");return;}String q=prompt.getText().toString().trim();if(q.isEmpty())q="این تصویر را کامل تحلیل کن، اطلاعات مهم را استخراج کن و فقط اگر مطمئن هستی یک اقدام امن و مفید پیشنهاد بده.";if(lastResult!=null&&!lastResult.summary.isEmpty()){q=q+"\n\nزمینه تحلیل قبلی روی همین تصویر:\n"+lastResult.display();}lastQuestion=prompt.getText().toString().trim();status.setText("VISION • در حال دیدن، استخراج و تصمیم‌گیری...");answer.setText("...");meta.setText("");actionInfo.setText("در حال بررسی اقدام مناسب...");executeAction.setEnabled(false);engine.analyzeAgent(image,q,r->{lastResult=r;answer.setText(r.display());meta.setText("نوع: "+r.entityType+"   |   اطمینان: "+r.confidence+"٪");String label=actionRouter.label(r.suggestedAction);if(label.isEmpty()||"none".equals(r.suggestedAction)){actionInfo.setText("اقدام اجرایی مطمئنی پیشنهاد نشده است.");executeAction.setEnabled(false);}else{actionInfo.setText("پیشنهاد: "+label+"\n"+(r.rationale.isEmpty()?"":r.rationale));executeAction.setText("✓ تأیید و اجرا: "+label);executeAction.setEnabled(r.confidence>=55);}status.setText(r.confidence>=70?"VISION • تحلیل قابل اتکا":"VISION • تحلیل انجام شد؛ قبل از اقدام بررسی کن");});}
    void confirmAction(){if(lastResult==null||"none".equals(lastResult.suggestedAction))return;String label=actionRouter.label(lastResult.suggestedAction);String msg="JARVIS از روی تصویر این اقدام را پیشنهاد داده:\n\n"+label+"\n\nاطمینان تحلیل: "+lastResult.confidence+"٪"+(lastResult.rationale.isEmpty()?"":"\n\n"+lastResult.rationale)+"\n\nفقط در صورت درست بودن اطلاعات، اجرا را تأیید کن.";new AlertDialog.Builder(this).setTitle("تأیید اقدام Vision").setMessage(msg).setPositiveButton("تأیید و اجرا",(d,w)->{String res=actionRouter.execute(lastResult);status.setText("ACTION • "+res);rememberAction(res);}).setNegativeButton("لغو",null).show();}
    void rememberAction(String result){if(lastResult==null)return;String ts=new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.US).format(new Date());memory.put("vision-action",ts,lastResult.summary+" | action="+lastResult.suggestedAction+" | "+result);}
    void save(){if(lastResult==null){status.setText("هنوز نتیجه‌ای برای ذخیره وجود ندارد.");return;}String ts=new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.US).format(new Date());memory.put("vision",ts,(lastQuestion.isEmpty()?"تحلیل تصویر":lastQuestion)+" | "+lastResult.display());status.setText("VISION • تحلیل در حافظه ذخیره شد");}
    void copyExtracted(){if(lastResult==null){status.setText("متنی برای کپی وجود ندارد.");return;}String t=!lastResult.extractedText.isEmpty()?lastResult.extractedText:lastResult.summary;ClipboardManager cm=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(ClipData.newPlainText("JARVIS Vision",t));status.setText("VISION • متن کپی شد");}
    @Override protected void onDestroy(){super.onDestroy();engine.shutdown();cleanupCameraFile();if(image!=null&&!image.isRecycled())image.recycle();image=null;}
}
