package com.jarvis.fa;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.text.SimpleDateFormat;import java.util.*;

public class VisionActivity extends Activity{
    private static final int REQ_CAMERA=301,REQ_GALLERY=302,REQ_PERMISSION=303;
    private Bitmap image;private ImageView preview;private EditText prompt;private TextView answer,status;private VisionEngine engine;private StructuredMemory memory;private String lastAnswer="";
    private int bg=Color.rgb(3,10,20),panel=Color.rgb(8,21,36),text=Color.WHITE,muted=Color.rgb(150,180,200),accent=Color.rgb(54,224,255);
    @Override public void onCreate(Bundle b){super.onCreate(b);engine=new VisionEngine(this);memory=new StructuredMemory(this);build();}
    int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(text);v.setTextSize(z);v.setPadding(dp(12),dp(9),dp(12),dp(9));return v;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
    void build(){ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(18),dp(16),dp(24));r.setBackgroundColor(bg);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
        TextView title=tv("JARVIS VISION",28);title.setTextColor(accent);title.setGravity(Gravity.CENTER);r.addView(title);TextView sub=tv("تصویر را نشان بده؛ سؤال بپرس؛ تحلیل را ادامه بده.",12);sub.setTextColor(muted);sub.setGravity(Gravity.CENTER);r.addView(sub);
        preview=new ImageView(this);preview.setBackgroundColor(panel);preview.setScaleType(ImageView.ScaleType.CENTER_CROP);r.addView(preview,new LinearLayout.LayoutParams(-1,dp(300)));
        LinearLayout pick=new LinearLayout(this);Button cam=btn("📷 دوربین");cam.setOnClickListener(v->camera());pick.addView(cam,new LinearLayout.LayoutParams(0,dp(52),1));Button gal=btn("🖼 گالری");gal.setOnClickListener(v->gallery());pick.addView(gal,new LinearLayout.LayoutParams(0,dp(52),1));r.addView(pick);
        prompt=new EditText(this);prompt.setTextColor(text);prompt.setHintTextColor(muted);prompt.setHint("مثلاً: این قطعه چیست؟ متن روی برگه را بخوان. ایراد ظاهری دستگاه چیست؟");prompt.setMinLines(2);r.addView(prompt);
        Button analyze=btn("◈ تحلیل توسط JARVIS Vision");analyze.setOnClickListener(v->analyze());r.addView(analyze,new LinearLayout.LayoutParams(-1,dp(56)));
        status=tv("VISION • آماده",12);status.setTextColor(accent);r.addView(status);answer=tv("هنوز تصویری تحلیل نشده است.",15);answer.setBackgroundColor(panel);r.addView(answer);
        LinearLayout bottom=new LinearLayout(this);Button save=btn("💾 ذخیره در حافظه");save.setOnClickListener(v->save());bottom.addView(save,new LinearLayout.LayoutParams(0,dp(50),1));Button again=btn("↻ سؤال بعدی");again.setOnClickListener(v->{prompt.requestFocus();prompt.selectAll();});bottom.addView(again,new LinearLayout.LayoutParams(0,dp(50),1));r.addView(bottom);sc.addView(r);setContentView(sc);}
    void camera(){if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},REQ_PERMISSION);return;}try{startActivityForResult(new Intent(MediaStore.ACTION_IMAGE_CAPTURE),REQ_CAMERA);}catch(Exception e){status.setText("دوربین در دسترس نیست.");}}
    void gallery(){try{Intent i=new Intent(Intent.ACTION_GET_CONTENT);i.setType("image/*");startActivityForResult(Intent.createChooser(i,"انتخاب تصویر"),REQ_GALLERY);}catch(Exception e){status.setText("گالری باز نشد.");}}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_PERMISSION&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)camera();else if(r==REQ_PERMISSION)status.setText("مجوز دوربین داده نشد.");}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null)return;try{if(req==REQ_CAMERA){Object x=data.getExtras()==null?null:data.getExtras().get("data");if(x instanceof Bitmap)image=(Bitmap)x;}else if(req==REQ_GALLERY){Uri u=data.getData();if(u!=null)try(InputStream in=getContentResolver().openInputStream(u)){image=BitmapFactory.decodeStream(in);}}if(image!=null){preview.setImageBitmap(image);status.setText("VISION • تصویر آماده تحلیل");answer.setText("سؤالت را بنویس و تحلیل را بزن.");}}catch(Exception e){status.setText("خواندن تصویر ممکن نشد.");}}
    void analyze(){if(image==null){status.setText("اول عکس بگیر یا از گالری انتخاب کن.");return;}String q=prompt.getText().toString().trim();status.setText("VISION • در حال تحلیل...");answer.setText("...");engine.analyze(image,q,r->{lastAnswer=r;answer.setText(r);status.setText("VISION • تحلیل کامل شد");});}
    void save(){if(lastAnswer.isEmpty()){status.setText("هنوز نتیجه‌ای برای ذخیره وجود ندارد.");return;}String ts=new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.US).format(new Date());String q=prompt.getText().toString().trim();memory.put("vision",ts,(q.isEmpty()?"تحلیل تصویر":q)+" | "+lastAnswer);status.setText("VISION • نتیجه در حافظه ذخیره شد");}
    @Override protected void onDestroy(){super.onDestroy();engine.shutdown();if(image!=null&&!image.isRecycled())image=null;}
}
