package com.jarvis.fa;
import android.app.*;import android.content.*;import android.os.*;import android.speech.*;import android.speech.tts.TextToSpeech;import java.util.*;
public class WakeWordService extends Service implements TextToSpeech.OnInitListener{
 public static final String ACTION_START="com.jarvis.fa.START_WAKE",ACTION_STOP="com.jarvis.fa.STOP_WAKE";SpeechRecognizer r;TextToSpeech tts;boolean running=false;Handler h=new Handler(Looper.getMainLooper());String wake="جارویس";
 @Override public void onCreate(){super.onCreate();channel();tts=new TextToSpeech(this,this);wake=getSharedPreferences("jarvis_data",MODE_PRIVATE).getString("wakeWord","جارویس");setup();}
 @Override public int onStartCommand(Intent i,int flags,int id){String a=i==null?ACTION_START:i.getAction();if(ACTION_STOP.equals(a)){running=false;h.removeCallbacksAndMessages(null);if(r!=null)r.cancel();stopForeground(true);stopSelf();return START_NOT_STICKY;}startForeground(2101,note("شنود فعال — بگو «"+wake+"»"));running=true;listen(500);return START_STICKY;}
 void channel(){if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel("jarvis_wake","شنود جارویس",NotificationManager.IMPORTANCE_LOW));}
 Notification note(String s){Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,1,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Intent stop=new Intent(this,WakeWordService.class).setAction(ACTION_STOP);PendingIntent ps=PendingIntent.getService(this,2,stop,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,"jarvis_wake"):new Notification.Builder(this);return b.setContentTitle("JARVIS").setContentText(s).setSmallIcon(android.R.drawable.ic_btn_speak_now).setOngoing(true).setContentIntent(pi).addAction(android.R.drawable.ic_menu_close_clear_cancel,"توقف",ps).build();}
 void setup(){if(!SpeechRecognizer.isRecognitionAvailable(this))return;r=SpeechRecognizer.createSpeechRecognizer(this);r.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float x){}public void onBufferReceived(byte[]b){}public void onEndOfSpeech(){}public void onError(int e){if(running)listen(1200);}public void onResults(Bundle b){ArrayList<String>x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty())process(x.get(0));if(running)listen(600);}public void onPartialResults(Bundle b){}public void onEvent(int a,Bundle b){}});}
 void listen(long d){h.postDelayed(()->{if(!running||r==null)return;try{Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);r.startListening(i);}catch(Exception e){if(running)listen(1500);}},d);}
 void process(String s){int x=s.indexOf(wake);if(x<0)return;String q=s.substring(x+wake.length()).trim();if(q.isEmpty()){speak("بله، در خدمتم.");return;}getSharedPreferences("jarvis_data",MODE_PRIVATE).edit().putString("pendingWakeCommand",q).apply();Intent i=new Intent("com.jarvis.fa.WAKE_COMMAND").setPackage(getPackageName()).putExtra("command",q);sendBroadcast(i);speak("دستور دریافت شد.");}
 void speak(String s){if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"wake");}@Override public void onInit(int s){if(s==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("fa","IR"));tts.setSpeechRate(.95f);}}@Override public void onDestroy(){running=false;h.removeCallbacksAndMessages(null);if(r!=null)r.destroy();if(tts!=null)tts.shutdown();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}
